title: Make the camera follow the player
hero_image: images/banner.png
description: Make the camera follow the player
version: 4
listed: false
copyedit: false
last_tested: "2021-11-04"
steps:
  - title: Make the camera follow the player
