title: Faire en sorte que la caméra suive le joueur
hero_image: images/banner.png
description: Faire en sorte que la caméra suive le joueur
version: 4
listed: false
copyedit: false
last_tested: "2021-11-04"
steps:
  - 
    title: Faire en sorte que la caméra suive le joueur
